package com.example.dto;

import java.io.Serializable;
import java.util.List;
import java.util.Set;

/**
 * HOUSE 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class House implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** HOUSE_NO. */
	private Integer houseNo;

	/** HOUSE_NAME. */
	private String houseName;

	/** HOUSE_ADDRESS. */
	private String houseAddress;
	
	/** HOUSE_ADDRESS. */
	private String houseAddressDetail;

	/** HOUSE_PRICE. */
	private Integer housePrice;

	/** HOUSE_SCORE. */
	private Integer houseScore;

	/** HOUSE_INFO. */
	private String houseInfo;

	/** MEMBER_ID. */
	private String memberId;

	/** DETAIL_ID. */
	private Integer detailId;
	
	/** HOSUE_ROOM */
	private String houseRoom;
	
	/** HOUSE_BATH */
	private String houseBath;
	
	/** HOUSE_HOSTING */
	private String houseHosting;
	
	/** HOUSE_TV */
	private String houseTv;
	
	/** HOUSE_AIRCON */
	private String houseAircon;
	
	/** HOUSE_WIFI */
	private String houseWifi;
	
	/** HOUSE_ELEBE */
	private String houseElebe;
	
	/** HOUSE_WASHING */
	private String houseWashing;
	
	/** HOUSE_IMG */
	private String houseImg;
	
	/** HOUSE_DAY */
	private String houseDay;
	
	/** POSS_CHECK_IN */
	private String possCheckIn;
	
	/** POSS_CHECK_OUT */
	private String possCheckOut;
	
	/** REGIST_HOUSE */
	private List<RegistHouse> registHouse;
	
	/**
	 * 생성자.
	 */
	public House() {
	}

	public House(Integer houseNo, String houseName, String houseAddress, Integer housePrice, Integer houseScore,
			String houseInfo) {
		super();
		this.houseNo = houseNo;
		this.houseName = houseName;
		this.houseAddress = houseAddress;
		this.housePrice = housePrice;
		this.houseScore = houseScore;
		this.houseInfo = houseInfo;
	}
	
	public House(Integer houseNo, String houseName, String houseAddress, Integer housePrice, Integer houseScore,
			String houseInfo, String memberId, Integer detailId) {

		this(houseNo,houseName,houseAddress,housePrice,houseScore,houseInfo);
		this.memberId = memberId;
		this.detailId = detailId;
	}
	
	

	public House(Integer houseNo, String houseName, String houseAddress, Integer housePrice, Integer houseScore,
			String houseInfo, String memberId, Integer detailId,
			String houseRoom, String houseBath, String houseHosting, String houseTv, String houseAircon,
			String houseWifi, String houseElebe, String houseWashing, String houseImg, String houseDay,
			String possCheckIn, String possCheckOut) {
		this(houseNo,houseName,houseAddress,housePrice,houseScore,houseInfo,memberId,detailId);
		this.houseRoom = houseRoom;
		this.houseBath = houseBath;
		this.houseHosting = houseHosting;
		this.houseTv = houseTv;
		this.houseAircon = houseAircon;
		this.houseWifi = houseWifi;
		this.houseElebe = houseElebe;
		this.houseWashing = houseWashing;
		this.houseImg = houseImg;
		this.houseDay = houseDay;
		this.possCheckIn = possCheckIn;
		this.possCheckOut = possCheckOut;
	}

	/**
	 * HOUSE_NO을 설정합니다..
	 * 
	 * @param houseNo
	 *            HOUSE_NO
	 */
	public void setHouseNo(Integer houseNo) {
		this.houseNo = houseNo;
	}

	/**
	 * HOUSE_NO을 가져옵니다..
	 * 
	 * @return HOUSE_NO
	 */
	public Integer getHouseNo() {
		return this.houseNo;
	}

	/**
	 * HOUSE_NAME을 설정합니다..
	 * 
	 * @param houseName
	 *            HOUSE_NAME
	 */
	public void setHouseName(String houseName) {
		this.houseName = houseName;
	}

	/**
	 * HOUSE_NAME을 가져옵니다..
	 * 
	 * @return HOUSE_NAME
	 */
	public String getHouseName() {
		return this.houseName;
	}

	/**
	 * HOUSE_ADDRESS을 설정합니다..
	 * 
	 * @param houseAddress
	 *            HOUSE_ADDRESS
	 */
	public void setHouseAddress(String houseAddress) {
		this.houseAddress = houseAddress;
	}

	/**
	 * HOUSE_ADDRESS을 가져옵니다..
	 * 
	 * @return HOUSE_ADDRESS
	 */
	public String getHouseAddress() {
		return this.houseAddress;
	}

	/**
	 * HOUSE_PRICE을 설정합니다..
	 * 
	 * @param housePrice
	 *            HOUSE_PRICE
	 */
	public void setHousePrice(Integer housePrice) {
		this.housePrice = housePrice;
	}

	/**
	 * HOUSE_PRICE을 가져옵니다..
	 * 
	 * @return HOUSE_PRICE
	 */
	public Integer getHousePrice() {
		return this.housePrice;
	}

	/**
	 * HOUSE_SCORE을 설정합니다..
	 * 
	 * @param houseScore
	 *            HOUSE_SCORE
	 */
	public void setHouseScore(Integer houseScore) {
		this.houseScore = houseScore;
	}

	/**
	 * HOUSE_SCORE을 가져옵니다..
	 * 
	 * @return HOUSE_SCORE
	 */
	public Integer getHouseScore() {
		return this.houseScore;
	}

	/**
	 * HOUSE_INFO을 설정합니다..
	 * 
	 * @param houseInfo
	 *            HOUSE_INFO
	 */
	public void setHouseInfo(String houseInfo) {
		this.houseInfo = houseInfo;
	}

	/**
	 * HOUSE_INFO을 가져옵니다..
	 * 
	 * @return HOUSE_INFO
	 */
	public String getHouseInfo() {
		return this.houseInfo;
	}

	/**
	 * MEMBER_ID을 설정합니다..
	 * 
	 * @param memberId
	 *            MEMBER_ID
	 */
	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	/**
	 * MEMBER_ID을 가져옵니다..
	 * 
	 * @return MEMBER_ID
	 */
	public String getMemberId() {
		return this.memberId;
	}

	/**
	 * DETAIL_ID을 설정합니다..
	 * 
	 * @param detailId
	 *            DETAIL_ID
	 */
	public void setDetailId(Integer detailId) {
		this.detailId = detailId;
	}

	/**
	 * DETAIL_ID을 가져옵니다..
	 * 
	 * @return DETAIL_ID
	 */
	public Integer getDetailId() {
		return this.detailId;
	}
	
	public String getHouseRoom() {
		return houseRoom;
	}

	public void setHouseRoom(String houseRoom) {
		this.houseRoom = houseRoom;
	}

	public String getHouseBath() {
		return houseBath;
	}

	public void setHouseBath(String houseBath) {
		this.houseBath = houseBath;
	}

	public String getHouseHosting() {
		return houseHosting;
	}

	public void setHouseHosting(String houseHosting) {
		this.houseHosting = houseHosting;
	}
	
	public String getHouseTv() {
		return houseTv;
	}

	public void setHouseTv(String houseTv) {
		this.houseTv = houseTv;
	}

	public String getHouseAircon() {
		return houseAircon;
	}

	public void setHouseAircon(String houseAircon) {
		this.houseAircon = houseAircon;
	}

	public String getHouseWifi() {
		return houseWifi;
	}

	public void setHouseWifi(String houseWifi) {
		this.houseWifi = houseWifi;
	}

	public String getHouseElebe() {
		return houseElebe;
	}

	public void setHouseElebe(String houseElebe) {
		this.houseElebe = houseElebe;
	}

	public String getHouseWashing() {
		return houseWashing;
	}

	public void setHouseWashing(String houseWashing) {
		this.houseWashing = houseWashing;
	}

	public String getHouseImg() {
		return houseImg;
	}

	public void setHouseImg(String houseImg) {
		this.houseImg = houseImg;
	}

	public String getHouseDay() {
		return houseDay;
	}

	public void setHouseDay(String houseDay) {
		this.houseDay = houseDay;
	}
	
	public String getHouseAddressDetail() {
		return houseAddressDetail;
	}

	public void setHouseAddressDetail(String houseAddressDetail) {
		this.houseAddressDetail = houseAddressDetail;
	}



	public String getPossCheckIn() {
		return possCheckIn;
	}

	public void setPossCheckIn(String possCheckIn) {
		this.possCheckIn = possCheckIn;
	}

	public String getPossCheckOut() {
		return possCheckOut;
	}

	public void setPossCheckOut(String possCheckOut) {
		this.possCheckOut = possCheckOut;
	}
	
	public List<RegistHouse> getRegistHouse() {
		return registHouse;
	}

	public void setRegistHouse(List<RegistHouse> registHouse) {
		this.registHouse = registHouse;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((houseNo == null) ? 0 : houseNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		House other = (House) obj;
		if (houseNo == null) {
			if (other.houseNo != null) {
				return false;
			}
		} else if (!houseNo.equals(other.houseNo)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "House [houseNo=" + houseNo + ", houseName=" + houseName + ", houseAddress=" + houseAddress
				+ ", houseAddressDetail=" + houseAddressDetail + ", housePrice=" + housePrice + ", houseScore="
				+ houseScore + ", houseInfo=" + houseInfo + ", memberId=" + memberId + ", detailId=" + detailId
				+ ", houseRoom=" + houseRoom + ", houseBath=" + houseBath + ", houseHosting=" + houseHosting
				+ ", houseTv=" + houseTv + ", houseAircon=" + houseAircon + ", houseWifi=" + houseWifi + ", houseElebe="
				+ houseElebe + ", houseWashing=" + houseWashing + ", houseImg=" + houseImg + ", houseDay=" + houseDay
				+ ", possCheckIn=" + possCheckIn + ", possCheckOut=" + possCheckOut + ", registHouse=" + registHouse
				+ "]";
	}

}
