package com.example.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * QUESTION_TO_REPLY 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class QuestionToReply implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** QUEST_REPLY_NO. */
	private Integer questReplyNo;

	/** MEMBER_ID. */
	private String memberId;

	/** QUEST_REPLY_CONTENT. */
	private String questReplyContent;

	/** QUEST_REPLY_DATE. */
	private Date questReplyDate;

	/** QUEST_NO. */
	private Integer questNo;

	/**
	 * 생성자.
	 */
	public QuestionToReply() {
	}
	
	public QuestionToReply(Integer questReplyNo, String memberId, String questReplyContent, Date questReplyDate,
			Integer questNo) {
		super();
		this.questReplyNo = questReplyNo;
		this.memberId = memberId;
		this.questReplyContent = questReplyContent;
		this.questReplyDate = questReplyDate;
		this.questNo = questNo;
	}

	/**
	 * QUEST_REPLY_NO을 설정합니다..
	 * 
	 * @param questReplyNo
	 *            QUEST_REPLY_NO
	 */
	public void setQuestReplyNo(Integer questReplyNo) {
		this.questReplyNo = questReplyNo;
	}

	/**
	 * QUEST_REPLY_NO을 가져옵니다..
	 * 
	 * @return QUEST_REPLY_NO
	 */
	public Integer getQuestReplyNo() {
		return this.questReplyNo;
	}

	/**
	 * MEMBER_ID을 설정합니다..
	 * 
	 * @param memberId
	 *            MEMBER_ID
	 */
	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	/**
	 * MEMBER_ID을 가져옵니다..
	 * 
	 * @return MEMBER_ID
	 */
	public String getMemberId() {
		return this.memberId;
	}

	/**
	 * QUEST_REPLY_CONTENT을 설정합니다..
	 * 
	 * @param questReplyContent
	 *            QUEST_REPLY_CONTENT
	 */
	public void setQuestReplyContent(String questReplyContent) {
		this.questReplyContent = questReplyContent;
	}

	/**
	 * QUEST_REPLY_CONTENT을 가져옵니다..
	 * 
	 * @return QUEST_REPLY_CONTENT
	 */
	public String getQuestReplyContent() {
		return this.questReplyContent;
	}

	/**
	 * QUEST_REPLY_DATE을 설정합니다..
	 * 
	 * @param questReplyDate
	 *            QUEST_REPLY_DATE
	 */
	public void setQuestReplyDate(Date questReplyDate) {
		this.questReplyDate = questReplyDate;
	}

	/**
	 * QUEST_REPLY_DATE을 가져옵니다..
	 * 
	 * @return QUEST_REPLY_DATE
	 */
	public Date getQuestReplyDate() {
		return this.questReplyDate;
	}

	/**
	 * QUEST_NO을 설정합니다..
	 * 
	 * @param questNo
	 *            QUEST_NO
	 */
	public void setQuestNo(Integer questNo) {
		this.questNo = questNo;
	}

	/**
	 * QUEST_NO을 가져옵니다..
	 * 
	 * @return QUEST_NO
	 */
	public Integer getQuestNo() {
		return this.questNo;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((questReplyNo == null) ? 0 : questReplyNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		QuestionToReply other = (QuestionToReply) obj;
		if (questReplyNo == null) {
			if (other.questReplyNo != null) {
				return false;
			}
		} else if (!questReplyNo.equals(other.questReplyNo)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "QuestionToReply [questReplyNo=" + questReplyNo + ", memberId=" + memberId + ", questReplyContent="
				+ questReplyContent + ", questReplyDate=" + questReplyDate + ", questNo=" + questNo + "]";
	}
	
}
