package com.example.dto;

import java.io.Serializable;

/**
 * REGIST_HOUSE 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RegistHouse implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** RH_ID. */
	private Integer rhId;

	/** CHECK_IN. */
	private String checkIn;

	/** CHECK_OUT. */
	private String checkOut;
	
	/** HOUSE_NO */
	private Integer houseNo;
	
	/** MEMBER_ID */
	private String memberId;
	
	/** HOUSE */
	private House house;
	private Member member;
	
	/**
	 * 생성자.
	 */
	public RegistHouse() {
	}
	
	public RegistHouse(Integer rhId, String checkIn, String checkOut) {
		super();
		this.rhId = rhId;
		this.checkIn = checkIn;
		this.checkOut = checkOut;
	}
	
	public RegistHouse(Integer rhId, String checkIn, String checkOut, Integer houseNo, String memberId) {
		super();
		this.rhId = rhId;
		this.checkIn = checkIn;
		this.checkOut = checkOut;
		this.houseNo = houseNo;
		this.memberId = memberId;
	}

	public Member getMember() {
		return member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	/**
	 * RH_ID을 설정합니다..
	 * 
	 * @param rhId
	 *            RH_ID
	 */
	public void setRhId(Integer rhId) {
		this.rhId = rhId;
	}

	/**
	 * RH_ID을 가져옵니다..
	 * 
	 * @return RH_ID
	 */
	public Integer getRhId() {
		return this.rhId;
	}

	/**
	 * CHECK_IN을 설정합니다..
	 * 
	 * @param checkIn
	 *            CHECK_IN
	 */
	public void setCheckIn(String checkIn) {
		this.checkIn = checkIn;
	}

	/**
	 * CHECK_IN을 가져옵니다..
	 * 
	 * @return CHECK_IN
	 */
	public String getCheckIn() {
		return this.checkIn;
	}

	/**
	 * CHECK_OUT을 설정합니다..
	 * 
	 * @param checkOut
	 *            CHECK_OUT
	 */
	public void setCheckOut(String checkOut) {
		this.checkOut = checkOut;
	}

	/**
	 * CHECK_OUT을 가져옵니다..
	 * 
	 * @return CHECK_OUT
	 */
	public String getCheckOut() {
		return this.checkOut;
	}
	
	public Integer getHouseNo() {
		return houseNo;
	}

	public void setHouseNo(Integer houseNo) {
		this.houseNo = houseNo;
	}

	public String getMemberId() {
		return memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}
	
	public House getHouse() {
		return house;
	}

	public void setHouse(House house) {
		this.house = house;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((rhId == null) ? 0 : rhId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		RegistHouse other = (RegistHouse) obj;
		if (rhId == null) {
			if (other.rhId != null) {
				return false;
			}
		} else if (!rhId.equals(other.rhId)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "RegistHouse [rhId=" + rhId + ", checkIn=" + checkIn + ", checkOut=" + checkOut + ", houseNo=" + houseNo
				+ ", memberId=" + memberId + ", house=" + house +" member: " +member+"]";
	}

}
