package com.example.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * REPORT_TO_REPLY 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ReportToReply implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** REPORT_REPLY_NO. */
	private Integer reportReplyNo;

	/** MEMBER_ID. */
	private String memberId;

	/** REPORT_REPLY_CONTENT. */
	private String reportReplyContent;

	/** REPORT_REPLY_DATE. */
	private Date reportReplyDate;
	
	/** REPORT_NO */
	private Integer reportNo;

	/**
	 * 생성자.
	 */
	public ReportToReply() {
	}
	
	public ReportToReply(Integer reportReplyNo, String memberId, String reportReplyContent, Date reportReplyDate,
			Integer reportNo) {
		super();
		this.reportReplyNo = reportReplyNo;
		this.memberId = memberId;
		this.reportReplyContent = reportReplyContent;
		this.reportReplyDate = reportReplyDate;
		this.reportNo = reportNo;
	}

	/**
	 * REPORT_REPLY_NO을 설정합니다..
	 * 
	 * @param reportReplyNo
	 *            REPORT_REPLY_NO
	 */
	public void setReportReplyNo(Integer reportReplyNo) {
		this.reportReplyNo = reportReplyNo;
	}

	/**
	 * REPORT_REPLY_NO을 가져옵니다..
	 * 
	 * @return REPORT_REPLY_NO
	 */
	public Integer getReportReplyNo() {
		return this.reportReplyNo;
	}

	/**
	 * MEMBER_ID을 설정합니다..
	 * 
	 * @param memberId
	 *            MEMBER_ID
	 */
	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	/**
	 * MEMBER_ID을 가져옵니다..
	 * 
	 * @return MEMBER_ID
	 */
	public String getMemberId() {
		return this.memberId;
	}

	/**
	 * REPORT_REPLY_CONTENT을 설정합니다..
	 * 
	 * @param reportReplyContent
	 *            REPORT_REPLY_CONTENT
	 */
	public void setReportReplyContent(String reportReplyContent) {
		this.reportReplyContent = reportReplyContent;
	}

	/**
	 * REPORT_REPLY_CONTENT을 가져옵니다..
	 * 
	 * @return REPORT_REPLY_CONTENT
	 */
	public String getReportReplyContent() {
		return this.reportReplyContent;
	}

	/**
	 * REPORT_REPLY_DATE을 설정합니다..
	 * 
	 * @param reportReplyDate
	 *            REPORT_REPLY_DATE
	 */
	public void setReportReplyDate(Date reportReplyDate) {
		this.reportReplyDate = reportReplyDate;
	}

	/**
	 * REPORT_REPLY_DATE을 가져옵니다..
	 * 
	 * @return REPORT_REPLY_DATE
	 */
	public Date getReportReplyDate() {
		return this.reportReplyDate;
	}
	
	public Integer getReportNo() {
		return reportNo;
	}


	public void setReportNo(Integer reportNo) {
		this.reportNo = reportNo;
	}


	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((reportReplyNo == null) ? 0 : reportReplyNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ReportToReply other = (ReportToReply) obj;
		if (reportReplyNo == null) {
			if (other.reportReplyNo != null) {
				return false;
			}
		} else if (!reportReplyNo.equals(other.reportReplyNo)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "ReportToReply [reportReplyNo=" + reportReplyNo + ", memberId=" + memberId + ", reportReplyContent="
				+ reportReplyContent + ", reportReplyDate=" + reportReplyDate + ", reportNo=" + reportNo + "]";
	}

}
