import java.io.Serializable;
import java.util.Date;

/**
 * HOUSE 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class House implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** HOUSE_NO. */
	private Integer houseNo;

	/** HOUSE_NAME. */
	private String houseName;

	/** HOUSE_ADDRESS. */
	private String houseAddress;

	/** HOUSE_ADDRESS_DETAIL. */
	private String houseAddressDetail;

	/** HOUSE_PRICE. */
	private Integer housePrice;

	/** HOUSE_SCORE. */
	private Integer houseScore;

	/** HOUSE_INFO. */
	private String houseInfo;

	/** MEMBER_ID. */
	private String memberId;

	/** DETAIL_ID. */
	private Integer detailId;

	/** HOUSE_ROOM. */
	private String houseRoom;

	/** HOUSE_BATH. */
	private String houseBath;

	/** HOUSE_HOSTING. */
	private String houseHosting;

	/** HOUSE_TV. */
	private String houseTv;

	/** HOUSE_AIRCON. */
	private String houseAircon;

	/** HOUSE_WIFI. */
	private String houseWifi;

	/** HOUSE_ELEBE. */
	private String houseElebe;

	/** HOUSE_WASHING. */
	private String houseWashing;

	/** HOUSE_IMG. */
	private String houseImg;

	/** HOUSE_DAY. */
	private String houseDay;

	/** POSS_CHECK_IN. */
	private Date possCheckIn;

	/** POSS_CHECK_OUT. */
	private Date possCheckOut;

	/**
	 * 생성자.
	 */
	public House() {
	}

	/**
	 * HOUSE_NO을 설정합니다..
	 * 
	 * @param houseNo
	 *            HOUSE_NO
	 */
	public void setHouseNo(Integer houseNo) {
		this.houseNo = houseNo;
	}

	/**
	 * HOUSE_NO을 가져옵니다..
	 * 
	 * @return HOUSE_NO
	 */
	public Integer getHouseNo() {
		return this.houseNo;
	}

	/**
	 * HOUSE_NAME을 설정합니다..
	 * 
	 * @param houseName
	 *            HOUSE_NAME
	 */
	public void setHouseName(String houseName) {
		this.houseName = houseName;
	}

	/**
	 * HOUSE_NAME을 가져옵니다..
	 * 
	 * @return HOUSE_NAME
	 */
	public String getHouseName() {
		return this.houseName;
	}

	/**
	 * HOUSE_ADDRESS을 설정합니다..
	 * 
	 * @param houseAddress
	 *            HOUSE_ADDRESS
	 */
	public void setHouseAddress(String houseAddress) {
		this.houseAddress = houseAddress;
	}

	/**
	 * HOUSE_ADDRESS을 가져옵니다..
	 * 
	 * @return HOUSE_ADDRESS
	 */
	public String getHouseAddress() {
		return this.houseAddress;
	}

	/**
	 * HOUSE_ADDRESS_DETAIL을 설정합니다..
	 * 
	 * @param houseAddressDetail
	 *            HOUSE_ADDRESS_DETAIL
	 */
	public void setHouseAddressDetail(String houseAddressDetail) {
		this.houseAddressDetail = houseAddressDetail;
	}

	/**
	 * HOUSE_ADDRESS_DETAIL을 가져옵니다..
	 * 
	 * @return HOUSE_ADDRESS_DETAIL
	 */
	public String getHouseAddressDetail() {
		return this.houseAddressDetail;
	}

	/**
	 * HOUSE_PRICE을 설정합니다..
	 * 
	 * @param housePrice
	 *            HOUSE_PRICE
	 */
	public void setHousePrice(Integer housePrice) {
		this.housePrice = housePrice;
	}

	/**
	 * HOUSE_PRICE을 가져옵니다..
	 * 
	 * @return HOUSE_PRICE
	 */
	public Integer getHousePrice() {
		return this.housePrice;
	}

	/**
	 * HOUSE_SCORE을 설정합니다..
	 * 
	 * @param houseScore
	 *            HOUSE_SCORE
	 */
	public void setHouseScore(Integer houseScore) {
		this.houseScore = houseScore;
	}

	/**
	 * HOUSE_SCORE을 가져옵니다..
	 * 
	 * @return HOUSE_SCORE
	 */
	public Integer getHouseScore() {
		return this.houseScore;
	}

	/**
	 * HOUSE_INFO을 설정합니다..
	 * 
	 * @param houseInfo
	 *            HOUSE_INFO
	 */
	public void setHouseInfo(String houseInfo) {
		this.houseInfo = houseInfo;
	}

	/**
	 * HOUSE_INFO을 가져옵니다..
	 * 
	 * @return HOUSE_INFO
	 */
	public String getHouseInfo() {
		return this.houseInfo;
	}

	/**
	 * MEMBER_ID을 설정합니다..
	 * 
	 * @param memberId
	 *            MEMBER_ID
	 */
	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	/**
	 * MEMBER_ID을 가져옵니다..
	 * 
	 * @return MEMBER_ID
	 */
	public String getMemberId() {
		return this.memberId;
	}

	/**
	 * DETAIL_ID을 설정합니다..
	 * 
	 * @param detailId
	 *            DETAIL_ID
	 */
	public void setDetailId(Integer detailId) {
		this.detailId = detailId;
	}

	/**
	 * DETAIL_ID을 가져옵니다..
	 * 
	 * @return DETAIL_ID
	 */
	public Integer getDetailId() {
		return this.detailId;
	}

	/**
	 * HOUSE_ROOM을 설정합니다..
	 * 
	 * @param houseRoom
	 *            HOUSE_ROOM
	 */
	public void setHouseRoom(String houseRoom) {
		this.houseRoom = houseRoom;
	}

	/**
	 * HOUSE_ROOM을 가져옵니다..
	 * 
	 * @return HOUSE_ROOM
	 */
	public String getHouseRoom() {
		return this.houseRoom;
	}

	/**
	 * HOUSE_BATH을 설정합니다..
	 * 
	 * @param houseBath
	 *            HOUSE_BATH
	 */
	public void setHouseBath(String houseBath) {
		this.houseBath = houseBath;
	}

	/**
	 * HOUSE_BATH을 가져옵니다..
	 * 
	 * @return HOUSE_BATH
	 */
	public String getHouseBath() {
		return this.houseBath;
	}

	/**
	 * HOUSE_HOSTING을 설정합니다..
	 * 
	 * @param houseHosting
	 *            HOUSE_HOSTING
	 */
	public void setHouseHosting(String houseHosting) {
		this.houseHosting = houseHosting;
	}

	/**
	 * HOUSE_HOSTING을 가져옵니다..
	 * 
	 * @return HOUSE_HOSTING
	 */
	public String getHouseHosting() {
		return this.houseHosting;
	}

	/**
	 * HOUSE_TV을 설정합니다..
	 * 
	 * @param houseTv
	 *            HOUSE_TV
	 */
	public void setHouseTv(String houseTv) {
		this.houseTv = houseTv;
	}

	/**
	 * HOUSE_TV을 가져옵니다..
	 * 
	 * @return HOUSE_TV
	 */
	public String getHouseTv() {
		return this.houseTv;
	}

	/**
	 * HOUSE_AIRCON을 설정합니다..
	 * 
	 * @param houseAircon
	 *            HOUSE_AIRCON
	 */
	public void setHouseAircon(String houseAircon) {
		this.houseAircon = houseAircon;
	}

	/**
	 * HOUSE_AIRCON을 가져옵니다..
	 * 
	 * @return HOUSE_AIRCON
	 */
	public String getHouseAircon() {
		return this.houseAircon;
	}

	/**
	 * HOUSE_WIFI을 설정합니다..
	 * 
	 * @param houseWifi
	 *            HOUSE_WIFI
	 */
	public void setHouseWifi(String houseWifi) {
		this.houseWifi = houseWifi;
	}

	/**
	 * HOUSE_WIFI을 가져옵니다..
	 * 
	 * @return HOUSE_WIFI
	 */
	public String getHouseWifi() {
		return this.houseWifi;
	}

	/**
	 * HOUSE_ELEBE을 설정합니다..
	 * 
	 * @param houseElebe
	 *            HOUSE_ELEBE
	 */
	public void setHouseElebe(String houseElebe) {
		this.houseElebe = houseElebe;
	}

	/**
	 * HOUSE_ELEBE을 가져옵니다..
	 * 
	 * @return HOUSE_ELEBE
	 */
	public String getHouseElebe() {
		return this.houseElebe;
	}

	/**
	 * HOUSE_WASHING을 설정합니다..
	 * 
	 * @param houseWashing
	 *            HOUSE_WASHING
	 */
	public void setHouseWashing(String houseWashing) {
		this.houseWashing = houseWashing;
	}

	/**
	 * HOUSE_WASHING을 가져옵니다..
	 * 
	 * @return HOUSE_WASHING
	 */
	public String getHouseWashing() {
		return this.houseWashing;
	}

	/**
	 * HOUSE_IMG을 설정합니다..
	 * 
	 * @param houseImg
	 *            HOUSE_IMG
	 */
	public void setHouseImg(String houseImg) {
		this.houseImg = houseImg;
	}

	/**
	 * HOUSE_IMG을 가져옵니다..
	 * 
	 * @return HOUSE_IMG
	 */
	public String getHouseImg() {
		return this.houseImg;
	}

	/**
	 * HOUSE_DAY을 설정합니다..
	 * 
	 * @param houseDay
	 *            HOUSE_DAY
	 */
	public void setHouseDay(String houseDay) {
		this.houseDay = houseDay;
	}

	/**
	 * HOUSE_DAY을 가져옵니다..
	 * 
	 * @return HOUSE_DAY
	 */
	public String getHouseDay() {
		return this.houseDay;
	}

	/**
	 * POSS_CHECK_IN을 설정합니다..
	 * 
	 * @param possCheckIn
	 *            POSS_CHECK_IN
	 */
	public void setPossCheckIn(Date possCheckIn) {
		this.possCheckIn = possCheckIn;
	}

	/**
	 * POSS_CHECK_IN을 가져옵니다..
	 * 
	 * @return POSS_CHECK_IN
	 */
	public Date getPossCheckIn() {
		return this.possCheckIn;
	}

	/**
	 * POSS_CHECK_OUT을 설정합니다..
	 * 
	 * @param possCheckOut
	 *            POSS_CHECK_OUT
	 */
	public void setPossCheckOut(Date possCheckOut) {
		this.possCheckOut = possCheckOut;
	}

	/**
	 * POSS_CHECK_OUT을 가져옵니다..
	 * 
	 * @return POSS_CHECK_OUT
	 */
	public Date getPossCheckOut() {
		return this.possCheckOut;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((houseNo == null) ? 0 : houseNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		House other = (House) obj;
		if (houseNo == null) {
			if (other.houseNo != null) {
				return false;
			}
		} else if (!houseNo.equals(other.houseNo)) {
			return false;
		}
		return true;
	}

}
